application: radugrigore
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static
  expiration: '365D'

- url: /gridgames/static
  static_dir: gridgames/static
  expiration: '365D'

- url: /gridgames.*
  script: gridgames.app

- url: /.*
  script: rgrig.app

libraries:
- name: jinja2
  version: latest
